### ISSUE TITLE
[Feature Request] Sharing segments of code as syntax-highlighted text snippets

### ISSUE THREAD

**Issue by Juris-S** [bors2908/slack-share#6]
**Issue**
Currently, if sharing a snippet with _code quotes_ enabled, it lacks any code-specific highlighting:
```
/**
* Prints 'Hello World!' to the console
*/
private _helloWorld(): void {
    console.log( 'Hello World!' );
}
``` 
However, if shared via a snippet and the correct language is assigned:
```typescript
/**
* Prints 'Hello World!' to the console
*/
private _helloWorld(): void {
    console.log( 'Hello World!' );
}
```
It'd be great to have an optional toggle to share segments of code (as opposed to the whole file) with syntax highlighting, which could potentially be auto-detected (by Slack), or assigned based on the code-file extension (e.g. `.ts` --> `TypeScript`) 

**Solution**
Add an optional toggle for sharing a selection of code as a snippet, instead of plain-text surrounded by code quotes
![image](https://user-images.githubusercontent.com/31705360/202415051-f90e7aa0-3f3f-47b9-92ee-b03056e01760.png)

![image](https://user-images.githubusercontent.com/31705360/202415568-74540585-a02b-46b6-8269-f3e5d3ea8839.png)

**Comment by bors2908** [comment]
@Juris-S 
Thank you for the feedback.

Feature was added (In simpler fashion, however) in the latest 0.9.9 version. It will be available in the coming days after moderation.
